### ISSUE TITLE
Multiple missing images in /media folder

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr#223]
In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr/master/Instructions/Labs/LAB_02a_Manage_Subscriptions_and_RBAC.md

We are missing file: ../media/lab02a.png

In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr/master/Instructions/Labs/LAB_02b-Manage_Governance_via_Azure_Policy.md

We are missing file: ../media/lab02b.png

In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr/master/Instructions/Labs/LAB_03a-Manage_Azure_Resources_by_Using_the_Azure_Portal.md

We are missing file: ../media/lab03a.png

In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr/master/Instructions/Labs/LAB_09a-Implement_Web_Apps.md

We are missing file: ../media/lab09a.png

In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.fr-fr/master/Instructions/Labs/LAB_09c-Implement_Azure_Kubernetes_Service.md

We are missing file: ../media/lab09c.png

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Waiting for locfile check In. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtTcGFuaXNoPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7U3RhcnRzIFdpdGg7NTAzMDIuSW5zdHJ1Y3Rpb25zLm1lZGlhPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by chriscarty00** [comment]
Discussed with the PM and the en-us version of the art files have been added manually to the OLPROD branch
